### ISSUE TITLE
Rendering of typos in IntelliJ shows wrong characters

### ISSUE THREAD

**Issue by SoumenDass** [belluzj/fantasque-sans#108]
This issue is different from https://github.com/belluzj/fantasque-sans/issues/25 - in this case a totally different word is rendered in IntelliJ for typos when using Fantasque Sans Mono. Details of the issue are in this [StackOverflow thread](https://stackoverflow.com/questions/55488353/how-to-stop-intellij-hiding-static-constant-names-by-replacing-them-with-random/55495523#55495523) I created today for this issue.

**Comment by SoumenDass** [comment]
Re-opened after accidentally closing it.

**Comment by belluzj** [comment]
Hello,

I guess that you are using Windows. The issue looks very much like that one from Hack: https://github.com/source-foundry/Hack/issues/362

I don't provide a Windows installer for Fantasque Sans Mono, so instead I would suggest to try to uninstall all the Fantasque Sans Mono font files from your machine (including potential duplicates ending in `_0` and reinstall them afterwards.

Does this help?

**Comment by SoumenDass** [comment]
@belluzj sorry for the delay in responding - it does help. For reference, these are the specific steps I carried out to resolve this issue:

1. Backup the Fantasque* fonts by copying them from c:\Windows\Fonts to a safe location (using Windows Explorer works fine)
2. Select Fantasque Sans Mono in Windows Explorer and delete it
3. Open Command Prompt (cmd), navigate to the same folder and verify via "dir" command if the deleted font is still there (in my case "dir Fantasque*" still showed files even after steps #1 and #2 were done).
4. Issue "del Fantasque*" and re-verify that the fonts are deleted
5. Copy back the fonts backed-up in step 1
6. Restart IntelliJ (and select Fantasque* if already not selected). The bold-italic should render correctly now.
