### ISSUE TITLE
Differing heights of capitals in VS (due to hinting?)

### ISSUE THREAD

**Issue by scottmcm** [belluzj/fantasque-sans#115]
My VS is currently rendering `THING` as follows, with the `HN` seeming shorter than the `TIG`:
![image](https://user-images.githubusercontent.com/18526288/66616723-c84ac880-eb86-11e9-9158-74be7727a9fd.png)

NN-rescaled of the above, to show that it's 3 pixels different (out of 19):
![image](https://user-images.githubusercontent.com/18526288/66616884-65a5fc80-eb87-11e9-9bfd-3da35f0fbdb6.png)

Zooming in that stops happening, so I guess it's something about hinting?
![image](https://user-images.githubusercontent.com/18526288/66616775-ff20de80-eb86-11e9-9c80-4a62283f5b5a.png)

Really minor overall, but it jumped out at me for some reason.

(OTF version 1.7.2, Windows 10)

**Comment by belluzj** [comment]
Can you try the TTF version instead of OTF? It has hinting from `ttfautohint` which should solve this kind of problems.

**Comment by scottmcm** [comment]
Yup, looks like the TTF is more consistent here:
![image](https://user-images.githubusercontent.com/18526288/66681726-2ed3f300-ec28-11e9-9088-1bf37e469f33.png)

**Comment by belluzj** [comment]
Also in the latest release, the webfonts should include hinting from ttfautohint so they should look less funky than the first screenshots.
