### ISSUE TITLE
question: underline position

### ISSUE THREAD

**Issue by monkoose** [belluzj/fantasque-sans#117]
Hello @belluzj 
I have a question, why underline is so close to letters? On some font sizes it even makes text
harder to read, because of not perfect font rendering, looks like it overlaps with letters.

![Hard to read](https://i.imgur.com/yYd8ItQ.png?1)

Is it intended, so it will not overlap with underscores? If so? Can there be another version with lower underline like with looped k? Or some advices how to make it in a fork.
Thank you.

**Comment by nertpinx** [comment]
Sorry for commenting on an old issue, but this is something I was not bothered with before, and after some time this issue appeared. I compared to another terminal which did not have this issue and I thought it is related to that terminal: kovidgoyal/kitty#3208 However according to the author there is nothing the terminal should do as it is supposed to be the font's responsibility.

I'd be wondering if you figured something out or whether there's a way to debug this.

So just in case someone stumbles upon this...

**Comment by monkoose** [comment]
Hello, myself i just use another font now. Have not found any solution.

**Comment by dangh** [comment]
I adjusted the underline position and rebuild the font. You can download prebuilt [here](https://github.com/dangh/fantasque-sans/releases/tag/1.8.0-underline-fix) or checkout this [commit](https://github.com/dangh/fantasque-sans/commit/2e6b55815f507e7e080b1afb264bc21e3c9ebb19) and rebuild yourself.

**Comment by StitiFatah** [comment]
Nerd font patched of the `Normal` version of the above if anyone is interested : https://github.com/StitiFatah/fantasque-sans-nerd-font/releases/tag/underline-fixed-nerd-fonts
