### ISSUE TITLE
version without ligatures?

### ISSUE THREAD

**Issue by codic12** [belluzj/fantasque-sans#136]
if this exists, i can't find it. how can i compile from source without ligatures? 

cc: @belluzj

**Comment by kbauer** [comment]
Duplicate of https://github.com/belluzj/fantasque-sans/issues/122?

**Comment by spinda** [comment]
I've put up a fork at https://github.com/spinda/fantasque-sans-ligatures that strips out everything from v1.8.0 relating to the new coding ligatures.
