### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by glebd** [belluzj/fantasque-sans#23]
The font is very nice as it is, thank you very much. But it would be great to have Cyrillic support.

**Comment by mrjovanovic** [comment]
@belluzj 
Re: sr_RS & mk_MK Cyrillic in the Italic form

Serbian and Macedonian Cyrillic actually looks different from it's Russian equivalent in the letters bgdpt (*бгдпт*).
Here is a quick summary image from Wikipedia, which has a whole section about it. The biggest problem is the italic t which looks completely out of place in Serbian:

![](https://upload.wikimedia.org/wikipedia/commons/0/0e/Serbian_Cyrillic_Italic.svg)

**Comment by belluzj** [comment]
@mrjovanovic Thanks, I will consider using opentype features or releasing two versions of the font.

@all I'm sorry that I'm not making any progress on this right now, but all your comments will be very useful when I get back to this project. Thanks again :)

**Comment by mrjovanovic** [comment]
@belluzj
Take your time - the font is fantastic, and your work is greatly appreciated! :))

Yes, I think one would have to use OpenType features at the moment, or at least that's what the other big free fonts familis (DejaVu, Ubuntu, GNUFreeFont) are using.

**Comment by belluzj** [comment]
@mrjovanovic Does this look ok?
![](https://cloud.githubusercontent.com/assets/3616772/7788907/f1874efc-024d-11e5-86db-03a353b82dc9.png)

**Comment by mrjovanovic** [comment]
Great work! I really like the *т*, *д* and *ш* characters. A few points:

* The g (*г*) looks awkward, is the line on top straight?

* I'm not sure if this was just a spelling error, or a more serious issue - the d and b are switched in the text. So it says "подољшава" instead of "побољшава", and "хидриба" instead of "хибрида". I assume it's an issue with the translation, and hope the forms aren't switched. I like the

**Comment by belluzj** [comment]
I had indeed switched the glyph names while setting up the substitution... now it should be ok:
![](https://cloud.githubusercontent.com/assets/3616772/7789007/25fb00a8-0252-11e5-827a-0d9d6aad678c.png)

**Comment by mrjovanovic** [comment]
Yup, looks perfect.

**Comment by belluzj** [comment]
Hello Cyrillic users!

I just released [Fantasque Sans Mono 1.7.0](https://github.com/belluzj/fantasque-sans/releases/tag/v1.7.0) with Cyrillic characters in all of the four variants of the font (regular, italic, bold, bold italic). I consider this is the beta version of Cyrillic support, and I will keep this issue open to track new problems with the released glyphs. Also I still haven't addressed the line height issue with accented capital letters. So, feel free to [download the new version](https://github.com/belluzj/fantasque-sans/releases/download/v1.7.0/FantasqueSansMono.zip) and try it out!

**Comment by sergeevabc** [comment]
```
абвгдеёжзийклмнопрстуфхцчшщъыьэюя
                    ^
```
Lowercase “у” looks unnatural to me. More opinions from Russian speakers would be appreciated.

**Comment by tanmatra** [comment]
I do agree, looks a little unnatural. Such tail is good for italic, but not for normal font.

**Comment by belluzj** [comment]
ok, ok :)

**Comment by dayfuaim** [comment]
Another one.
The NUMBER SIGN in Cyrillic ("№") looks some ugly and wide (2 places instead of one). :)
![2017-01-25 15-54-54](https://cloud.githubusercontent.com/assets/1274699/22291313/b68196b8-e316-11e6-957d-3bda7899d430.png)
Could you correct this?

**Comment by belluzj** [comment]
Latest release with all the improvements (№, у, line height):

https://github.com/belluzj/fantasque-sans/releases/tag/v1.7.2-alpha.3

**Comment by efermi** [comment]
I'm not sure about the current revision of `у`. There are very few fonts where Latin and Cyrillic versions of the letter differ, and even in those usually the Cyrillic one has curlier descender (e.g. Minion Pro, the Lucida family). While I do agree that the Cyrillic version stands out a little, but so does the Latin one, it's just the Cyrillic subset doesn't have other letters with long descenders so it naturally stands out.

**Comment by likern** [comment]
@belluzj Hello!

> Font variant with a larger line height, especially for users of accented capitals

Does a `LargeLineHeight` affect latin alphabet too?
I'm a Russian developer and want to use this font mostly for programming (so english letters), but as 
font will be installed globally in OS, it might be used in Russian text  documents (like Word files).

Which font variant do I need to install?
