### ISSUE TITLE
Google Fonts

### ISSUE THREAD

**Issue by okonomiyaki3000** [belluzj/fantasque-sans#31]
This font seems rather charming. Any chance you will get it hosted by Google?

**Comment by xamde** [comment]
How close are we seeing this in Google Fonts?

**Comment by belluzj** [comment]
Considering that I still have one complete weight of Cyrillic to draw, the next version of the font won't be released before several months. If the current version is acceptable by Google Fonts standard, maybe it could be added now, and uploaded later with Cyrillic. @davelab6, would it be possible?

**Comment by adrientetar** [comment]
I opened google/fonts#77 – this issue can be closed now. There are quite some fonts to be added but it seems the Google Fonts team does not have the resources to handle all of this in a timely fashion. We will have to wait.

**Comment by belluzj** [comment]
Thanks for your help :)
