### ISSUE TITLE
Render apostrophes and single quotes differently

### ISSUE THREAD

**Issue by yggi49** [belluzj/fantasque-sans#42]
Typographic (usually “curly”) [apostrophes (U+2019)](http://www.fileformat.info/info/unicode/char/2019/index.htm) and [single quotes (U+0027)](http://www.fileformat.info/info/unicode/char/27/index.htm) are indistinguishable.  I’d suggest to either reduce the slant of the “normal” single quote, or to make the apostrophe really curly.

Apart from that: kudos for this awesome font, it’s a real joy working with it!

**Comment by belluzj** [comment]
I will consider it in the next release. Thanks for your interest :)
