### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by vyp** [belluzj/fantasque-sans#43]
The output of running `make`:

    mkdir -p OTF Webfonts
    ./validate-generate "FantasqueSansMono-RegItalic"
    [1;37mGenerating FantasqueSansMono-RegItalic... [0m
    Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
     License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
     with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
     Based on sources from 08:58 UTC 28-Mar-2015-ML-D.
     Based on source from git with hash: 
      File "<stdin>", line 6
        print font.fontname
                 ^
    SyntaxError: Missing parentheses in call to 'print'
    [1;31mError in FantasqueSansMono-RegItalic.[0m
    Makefile:17: recipe for target 'FantasqueSansMono-RegItalic.ttf' failed
    make: *** [FantasqueSansMono-RegItalic.ttf] Error 1

I do have the dependencies (fontforge, ttfautohint, sfnt2woff and ttf2eot?) installed by the way. How can I check if my fontforge has python scripting support?

**Comment by belluzj** [comment]
Looks like your fontforge has Python 3 support, while my script is for Python 
2. I will update it soon.

In data venerd� 3 aprile 2015 09:17:23, RWS ha scritto:
