### ISSUE TITLE
Exclamation mark becomes visibly equal to vertical bar at size 12

### ISSUE THREAD

**Issue by jevring** [belluzj/fantasque-sans#47]
Maybe I'm running this smaller than you are, but it becomes very hard to read at this size. Everything else (so far) is beautiful, though.

This is in Intellij IDEA. Look at the "!file.exists()" part.
![exclamation_mark](https://cloud.githubusercontent.com/assets/11088499/7553808/383dc572-f70b-11e4-8ff4-9d7800f51765.png)

Is there perhaps a recommended smallest size under which it stops looking good/correct? If so, what is this?

**Comment by belluzj** [comment]
Noted, I will do something about it in the next version, thanks for reporting :)

**Comment by jevring** [comment]
I'm happy to be of service =)

**Comment by hiltonjanfield** [comment]
Commenting as a reminder this is still an issue, a couple releases later.
