### ISSUE TITLE
Single quote (U+0027) issues

### ISSUE THREAD

**Issue by hiltonjanfield** [belluzj/fantasque-sans#49]
Nice looking font, playing with it in an IDE right now. However, I am finding the standard single quote/apostrophe character quite jarring both in code and in text.

My personal opinions:
- Character is too slanted compared to the rest of the text, and stands out jarringly.
- Character is also very heavy for punctuation in general.
- The style of the single quote does not match the double quote (slanted versus vertical).
- The slanted style (versus the straight vertical style in many fonts) looks very odd as a string delimiter, especially where the double-quote is also used nearby.
- In italics, the character seems to be just a smidge too far to the right.

This testing was in Windows at size 12 and 14. I can return with images if necessary.

**Comment by belluzj** [comment]
I will take your comments into consideration. Other people also have problems with the fact that "straight" quotes are in fact curly in this font, so I will try to draw a blander version of these quotes, maybe as a stylistic alternate. The thing with the current slanted single quotes is that it is really easy to distinguish them from double quotes.
