### ISSUE TITLE
Invisible comma at some sizes

### ISSUE THREAD

**Issue by mbaz** [belluzj/fantasque-sans#51]
Using gvim, on Linux, at sizes 10 and 11, with regular Fantasque Sans Mono, the comma is invisible. The comma is there (I can copy-paste it to another program), but it isn't rendered. At other sizes, such as 9 and 12, or weigths, such as bold or italic, there's no problem.

**Comment by belluzj** [comment]
I can't reproduce. Can you send screenshots, and tell me more about your distribution, freetype configuration... ?

**Comment by mbaz** [comment]
I'm running on Arch Linux, on openbox, and the problem happens on gvim
(haven't tried other programs). I created a short screencast to show the
problem in action: http://imgur.com/BNRFdKq

I use the stock Arch font configuration; I haven't modified it. Please let
me know if you want me to post specific information or files -- Arch breaks
down the config into multiple files under /etc/fonts/conf.d.

**Comment by mbaz** [comment]
After a reboot, the problem went away.
