### ISSUE TITLE
Request for 0x1A4 to be added

### ISSUE THREAD

**Issue by doubleagent** [belluzj/fantasque-sans#52]
"Capital P with a hook"

This character is used by Emacs 'clojure-mode' to "fancify" code.  See [here](https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/clojure#pretty-symbols) for details.

I really like this font and this seems to be the only thing missing from an otherwise wonderful experience.

**Comment by belluzj** [comment]
I will look into it for the next release (v1.7)
