### ISSUE TITLE
Is otf the best format to install?

### ISSUE THREAD

**Issue by Jackbennett** [belluzj/fantasque-sans#55]
I've done a bit of reading on font formats, the release ships a lot but to install for myself am I correct that ideally I want to just install the otf files? Seems like the most modern advanced format. 

Does it even matter?

**Comment by belluzj** [comment]
It depends on your os: if you are on Linux or OSX, both the ttf and otf formats are fine. On Windows however, you want the ttf files because they contain specific instructions on how to make the font look nice. Other shipped formats are for the web, not for installation on your personal computer.

**Comment by Jackbennett** [comment]
Grand, I'll switch to ttf then since I'm on windows. Should have clarified.

Been using this since it was Cosmic Sans, great work thank you.
