### ISSUE TITLE
Issues with backticks and curly-quotes

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [belluzj/fantasque-sans#57]
So, I've never submitted an issue about *type* before, so, I'm not sure about the etiquette here … it's a bit more subjective, and artistic, than anything I've ever commented on before. So, take my complaints as ‘this is my experience using your work,’ instead of as any instruction to change your style, I suppose? :P

I use a *lot* of backticks, for a variety of reasons; amongst others,

 - I write a lot of Markdown documentation for code.
 - I write a lot of shell-script (often, *with Markdown documentation* within it. O_O)

Unfortunately, although I've been *so* happy with switching to Fantasque as my code-editing typeface (as opposed to Terminal-window typeface), it's made any task involving backticks a bit … hellish.

Take a gander at how difficult it is to figure out what's going on in these:

> <img width="160" alt="screen shot 2015-12-13 at 11 52 19 pm" src="https://cloud.githubusercontent.com/assets/200/11773839/e315d590-a1f4-11e5-9083-9702f3321c67.png">
> <img width="287" alt="screen shot 2015-12-13 at 11 52 57 pm" src="https://cloud.githubusercontent.com/assets/200/11773833/dc236522-a1f4-11e5-9e17-b65528a721a5.png">
> <img width="396" alt="screen shot 2015-12-13 at 11 53 18 pm" src="https://cloud.githubusercontent.com/assets/200/11773834/e05588f0-a1f4-11e5-9137-a4b6061e5735.png">

In order, those are:

 - Two **\`backticks\`**, followed by **‘curly single-quotes,’** and a single **'straight-quote.'**
 - A **"straight double-quote"**, a **'straight-quote'**, and two **\`backticks\`**.
 - Two pairs of **\`backticks\`** followed by two pairs of **‘curly single-quotes.’**

It's gotten to the point where I've bound a hotkey to swap my editor's typeface out, when I'm staring at a block of text and I just *can't* determine what the mess of quotes are.

----

So, if I were to have my way in all things, I'd love to see:

 - Straight-quotes that are distinguishable from curly-quotes (after all, **’this’** doesn't look very pretty *anyway*; if you can't differentiate between start and end quotes, then why are you trying to make them faux-curly *at all*?), and that are preferably … well, straight. Although the latter is more of taste thing for myself than a usability issue. ¯\\_(ツ)_/¯
 - And, so very, very importantly for me, *visually-distinguished backticks*. Glancing at a couple other specimens, it looks like most editing typefaces go with a very “sharp” appearance for the backtick; but even when it's not super thin / pointed at the bottom, it's *always* straight as an arrow. I really do think it'd be best to make the backtick straight, to distinguish from the opening-curly-quote and straight-single-quote.

----

Here's a couple samples from other fixed-width faces I've used. Out of all of them, DejaVu Sans is (unsurprisingly) the most usable, and probably, the most elegant; but I don't think the approach that works for it is going to work for Fantasque's feel, so …

<img width="401" alt="screen shot 2015-12-14 at 12 04 44 am" src="https://cloud.githubusercontent.com/assets/200/11773991/5ab00160-a1f6-11e5-80c1-6a868e614162.png">

**Comment by belluzj** [comment]
First, thank you very much for this issue, which has screenshots and details, and don't worry for the part about telling me how to do my job, because type is not my job :)

This clearly is a usability problem, and having you switch the font to get out of the mess is unacceptable. I was going to do something about quotes in the next version anyway, because other people have had of lot of less articulated complaints such as “I don't like the quotes”. Now thanks to you I know exactly how I should handle the problem :)

**Comment by ELLIOTTCABLE** [comment]
Well, if you're super-open to input, here are my also-not-a-type-designer's thoughts:

 - Keeping curliness on the ‘straight quotes’ isn't a bad idea, even if it reduces usability; simply because … well, this font has Different Goals than usual, no? Instead of curling *in a direction*, though, have them curve outward (probably to the right, since that's pretty standard for fake-curvy-straight-quotes), while the top and bottom of the curve originate at the same horizontal point. (That is, when taken as a whole, they simply point directly downwards, with a bow in the middle.)
 - I really like what DejaVu does, playing on the *thickness* of the quote to indicate orientation: while the 
‘straight’ quotes and backticks stay pretty uniform in thickness, perhaps have the curly versions do a similar thick-start, thick-middle,*thin*-end stroke; but curve-ified instead of blocky as DejaVu's are?
 - And backticks, well, that leaves it easy to make them visually distinctive simply by having them be the only totally-linear quote.

**Comment by belluzj** [comment]
What's coming in the next version of the font:

![](https://cloud.githubusercontent.com/assets/3616772/11920010/c06c28c8-a762-11e5-8863-c3699ce396df.png)

**Comment by yggi49** [comment]
This is awesome, looking forward to it!  Thank you for your efforts!

**Comment by ELLIOTTCABLE** [comment]
This is beautiful!

Some feedback:
 - I think the straight-double-quote <b>"</b>" might need some work, but I can't pinpoint what bothers me about it :x (unhelpful, I know)
 - I really like how strongly angled the backticks are. Moreso than any typeface I've seen; they're nearly horizontal! I think you've very-well managed to keep Fantasque looking unique despite them not being as curvy / in-character as most of the characters
 - In the lighter weights, the curl of the curly-quotes is a little much, somehow? It looks great in the heavy weight, but the light weight non-talic looks like it has a *really* pronounced curve. It's not that the pronouncement of it is necessarily bad, either; it's just the ratio between thickness-of-stroke and curvature somehow really ‘screams’

hope it's helpful! Even as-is, you've solved all my problems and made me a very happy coder. ^_^
