### ISSUE TITLE
Trouble generating Fantasque Sans Mono Italic on Archlinux

### ISSUE THREAD

**Issue by ryuslash** [belluzj/fantasque-sans#58]
Hi,

I'm trying to build the latest changes of your excellent font on Archlinux and I'm running into some trouble. Running the `PKGBUILD` for `ttf-fantasque-sans-git` presents me with the following output:

```
mkdir -p OTF Webfonts
./validate-generate "FantasqueSansMono-Italic"
Generating FantasqueSansMono-Italic... 
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 23:20 UTC 28-Sep-2015-ML-D.
 Based on source from git with hash: 
Error in FantasqueSansMono-Italic.
Font FantasqueSansMono-Italic.sfd is not valid
Makefile:17: recipe for target 'FantasqueSansMono-Italic.ttf' failed
make: *** [FantasqueSansMono-Italic.ttf] Error 42
```

After starting an interactive Python session with `fontforge -lang=py -script` and manually stepping through the python script in `validate-generate`, it seems that on my system `font.validate()` returns `524288`, which is `80000` in hexadecimal. Looking at the fontforge [documentation](http://fontforge.github.io/en-US/documentation/scripting/python/) this is the only reference I could find to it:

> 0x80000
>
> Points non-integral. TrueType points and control points must be integer aligned. (FontForge will round them if they aren’t)

If I call `font.validate(True)` instead, I also get the error `0x800000` (along with `0x80000`), to which I found the reference:

> 0x800000

> Overlapped hints. Either the glyph has no hint masks and there are overlapped hints, or a hint mask specifies two overlapping hints.

In case it helps, this is the output of `fontforge -version`:

```
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 23:20 UTC 28-Sep-2015-ML-D.
 Based on source from git with hash: 
no xdefs_filename!
TESTING: getPixmapDir:/usr/share/fontforge/pixmaps
TESTING: getShareDir:/usr/share/fontforge
TESTING: GResourceProgramDir:/usr/bin
trying default theme:/usr/share/fontforge/pixmaps/resources
fontforge 23:20 UTC 28-Sep-2015
libfontforge 20150928
```

Do you have any idea how to fix this? I'd love to try out your latest changes.

Thanks for a great font.

Cheers,

Tom

**Comment by belluzj** [comment]
Sorry, I pushed changes to master without solving all errors from FontForge. Take the latest commit to build the font. You may see rendering issues.

**Comment by ryuslash** [comment]
Thanks, it works now. Should I report any rendering issues I run into?

**Comment by belluzj** [comment]
No, don't bother for now, I will try to push a version that compiles properly today.

**Comment by ryuslash** [comment]
Thanks!
