### ISSUE TITLE
Closing single quote issue

### ISSUE THREAD

**Issue by kartynnik** [belluzj/fantasque-sans#59]
In GCC output, single quotes are distinct from apostrophes:

    ../fstext/deterministic-fst-compo.h:96:12: error: ‘state_table_’ was not declared in this scope

I get the following rendering issue with Fantasque Sans Mono Bold 1.7 on this line:
![image](https://cloud.githubusercontent.com/assets/5329195/11958790/031719ca-a8db-11e5-8f10-0e0599f58d22.png)

**Comment by belluzj** [comment]
I can't reproduce. Which OS and terminal are you using? At what size?

**Comment by kartynnik** [comment]
Gnome Terminal, Ubuntu, Fantasque Sans Mono Bold 14.
This behavior may be also attributed to Infinality being installed. Would be great if someone could try to reproduce on a vanilla Ubuntu installation.

**Comment by kartynnik** [comment]
This may also be connected with LC_ALL=en_US.UTF-8 (I mean, that the programs do use the curved closing bracket instead of the plain apostrophe). The same rendering was observed with the string
```
mv: cannot move ‘.config/nvimrc’ to ‘.config/nvim/init.vim’: No such file or directory
```

**Comment by kartynnik** [comment]
Interestingly, this issue doesn't come up with the released fonts - I had built them from sources.
Closing the issue, sorry for the false alarm.
I'll try to find out which versions of FontForge etc. I was using to build the fonts - just in case it would be helpful to warn against using them somewhere.

**Comment by kartynnik** [comment]
The FontForge version available in Ubuntu repositories is 20120731, which seems ancient.
@belluzj, which one do you use?

**Comment by belluzj** [comment]
This ppa: https://launchpad.net/~fontforge/+archive/ubuntu/fontforge

**Comment by kartynnik** [comment]
Replacing the outdated FontForge version with the one from the PPA seems to resolve the issue.
Added the PR #61 to warn about that.
