### ISSUE TITLE
Question About download the lastest version

### ISSUE THREAD

**Issue by NoAnyLove** [belluzj/fantasque-sans#60]
Hi, it seems the latest version is 1.7.0, but the download link http://openfontlibrary.org/en/font/fantasque-sans-mono only offers 1.6.5. Just want to know if I can download the latest version. Thanks.

**Comment by belluzj** [comment]
You can download it from the "Releases" tab on GitHub: https://github.com/belluzj/fantasque-sans/releases/tag/v1.7.0

I will update OpenFontLibrary soon (right now I have forgotten my password...)

**Comment by NoAnyLove** [comment]
That's good. 

The new Github UI made me always ignore the Release tab, and I thought the release page was disappeared...
