### ISSUE TITLE
Ligatures and contextual alternatives

### ISSUE THREAD

**Issue by flying-sheep** [belluzj/fantasque-sans#64]
love your font, but having tasted the beauty that is [Fira Code’s](https://github.com/tonsky/FiraCode) ligatures, i can’t go back.

having both fantasque and those ligatures would be perfection!

the contextual alternatives are also amazing: having e.g. the `*` in `*ptr` and `-` in `foo-bar` adjusted based on the height of the characters next to them… yum!

**Comment by piggyslasher** [comment]
Please. Your font looks gorgeous :) Only thing stopping me is Ligatures.

**Comment by SethGunnells** [comment]
I cannot upvote this enough. This is my favorite font to use for all my monospace needs, but I'm using Fira Code right now because I love the ligatures. Having them in this font would be wonderful and I would be back immediately. I will even pay to see this happen!

**Comment by rebo** [comment]
Great font but ligatures are the future !

**Comment by belluzj** [comment]
I have started working on this. Here is my work-in-progress on the Regular. The yellow highlights indicate which ligatures have a special combined glyph in this font, compared to all the ligatures that are handled by [Fira Code](https://github.com/tonsky/FiraCode) and [Hasklig](https://github.com/i-tu/Hasklig).

![spectacle s12265](https://user-images.githubusercontent.com/3616772/34645240-a1be9238-f348-11e7-8b40-a0ef4ad68716.png)

I have reused the same techniques as Fira Code, so the font should have the same behaviour while editing. Only the Regular weight has ligatures for now. You can grab a test copy here: https://github.com/belluzj/fantasque-sans/releases/tag/v1.8-alpha

To continue, I would need feedback on those points:

* Is the behaviour of the font indeed satisfactory while editing code with ligatures?
* Are the currently implemented ligatures correct? (especially the F# pipes and Haskell ones, because I have no knowledge of their semantics or intended use)
* Which other ligatures are really needed? (I feel that some of the ligatures from Fira Code such as `<+>` or `<*>` are not really needed here because my `+` and `*` are already big enough and almost centered vertically (OK not exactly).

When all is fine on the regular I will do the same for the bold and italic and release. Thanks in advance for your feedback.

**Comment by SethGunnells** [comment]
Thank you for working on this! I am so excited to see ligatures coming to my favorite font!

I am trying it right now in Atom, but am having no luck. Ligatures don't seem to be appearing anywhere.

**Comment by belluzj** [comment]
Did you download the font from this page? https://github.com/belluzj/fantasque-sans/releases/tag/v1.8-alpha
Did you check in the regular weight (not bold, not italic)?

Thanks for trying it out :)

**Comment by SethGunnells** [comment]
Yes and yes.

**Comment by SethGunnells** [comment]
Tried it in TextEdit this time to confirm it wasn't Atom crapping out. Here's the results.

![image](https://user-images.githubusercontent.com/245822/34692702-a5a10c52-f486-11e7-953e-ee5952db5831.png)

**Comment by belluzj** [comment]
Can you drag and drop the TTF on that page: http://www.impallari.com/testing/

And check that ligatures work there?

![spectacle lh9590](https://user-images.githubusercontent.com/3616772/34693048-88258ed2-f4c2-11e7-807f-24b8a702a399.png)

**Comment by SethGunnells** [comment]
Nevermind! Turns out I was not replacing the font correctly. I needed to remove it completely from Font Book and add the new one for it to work properly. Here it is working!

![image](https://user-images.githubusercontent.com/245822/34693190-5e28acc0-f488-11e7-8b0e-231f0d330c30.png)

**Comment by belluzj** [comment]
ok great :)

**Comment by nikolalukovic** [comment]
Nice work on ligatures! When are you planning an official release?

**Comment by joewreschnig** [comment]
I'm very happy to see this going in. Two requests:

- Of the ligatures in Fira Code, I'd also like to see `.=` (to center the dot) and `/=` (same as "not equal to" in some Lisp languages)

- Today I use a variant font, Fira Code Symbol, which doesn't use "real" ligature support but places the combined glyphs at PUA codepoints. Then I use editor support to map replacements on a per-language basis. So "===" appears as a ligature in JavaScript but not C, etc. As far as I know this is not possible with "real" ligatures, which are always global. Would it be possible to ship a variant of the font with ligatures disabled but still contains the glyphs in the PUA range? (For Fira Code Symbol, they begin at U+E100.)

**Comment by piggyslasher** [comment]
While we're waiting for full ligature support, (which looks awesome!) you can use https://github.com/lemeb/a-better-ligaturizer to add ligatures from another font. Works great.

**Comment by ikzk** [comment]
This is awesome. It will be great if we also have emacs instructions https://github.com/tonsky/FiraCode/wiki/Emacs-instructions

**Comment by DrBearhands** [comment]
I seem to be missing the ligature for /= in Elm (should be the same as the more popular !=), which I did have with firacode, though that might be a configuration error on my part.

**Comment by pfgray** [comment]
Is it intentional that the ligatures show up in "normal" and not "italic"?

<img width="138" alt="screen shot 2018-10-21 at 10 28 24 am" src="https://user-images.githubusercontent.com/4752550/47268221-1735c300-d51c-11e8-8fea-ac4ab50aa895.png">

**Comment by sleepiejohn** [comment]
I think ligatures are only drawn to regular/normal, there is no other variant yet, thus you get only on regular formatting

**Comment by macdems** [comment]
I would love to have small x in hexagonal numbers: 0xff like 0×ff

**Comment by radiosilence** [comment]
Ok, these are looking amazing :)

**Comment by Bradcomp** [comment]
I just wanted to say that I have been using the ligatures for Javascript coding for the last few months. It looks great and I haven't run into any issues. Thank you for this amazing font.

One that I liked having from [Blackfont](https://github.com/blackro-se/blackfont) is the ligature for `//`. It's certainly not critical, but it makes comments a bit easier to read by putting the slashes close together with a little space after them.

I totally know that's probably not one to prioritize over the other suggestions here though.

**Comment by belluzj** [comment]
Hello ligatures-lovers!

I just published [a new version](https://github.com/belluzj/fantasque-sans/releases/tag/v1.8.0) that adds a bunch of ligatures to all weights, including those contributed by @artem-ogre in https://github.com/belluzj/fantasque-sans/pull/114 (with tweaks).

Please report any issues with the existing ligatures.

I know that I didn't implement all the requests from above, and if you find more ligatures that are missing, you can add them to this thread. However I don't think that I'll be adding any more of those myself, at least for the time being (meaning the next couple years probably).

**Comment by ansimita** [comment]
Hi,

I'd like to request ligature support for double underscores (a.k.a. dunders) which in Fira Code v2 (shown below) are combined:

![](https://raw.githubusercontent.com/tonsky/FiraCode/master/showcases/all_ligatures.png)

Dunders are heavily used in Python code.

**Comment by chiniara** [comment]
Can we have a version without ligatures? I can't disable them on Visual Studio , only Code has this option

**Comment by belluzj** [comment]
The new version only adds ligatures, so if you don't want them you can keep the old version for now. Next release I'll add packages without the ligatures.

**Comment by alexeyten** [comment]
Just for information. To disable ligature on Linux (since my terminal doesn't support them) I use following config adapted from [Archlinux wiki](https://wiki.archlinux.org/index.php/Font_configuration/Examples#Disable_ligatures_for_monospaced_fonts)
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="font">
        <test name="family" compare="eq">
            <string>Fantasque Sans Mono</string>
        </test>
        <edit name="fontfeatures" mode="assign_replace">
            <string>calt off</string> <!-- disable ligatures -->
            <string>ss01</string> <!-- k without loop -->
        </edit>
    </match>
</fontconfig>
```

**Comment by flying-sheep** [comment]
Great stuff, thank you @belluzj! The latest release contains ligatures, so I’ll close this issue.

**Comment by dantezhu** [comment]
hi, please add a no-ligatures version~, thanks!

**Comment by dantezhu** [comment]
hi, please add a no-ligatures version~, thanks!
