### ISSUE TITLE
1.7.0 font is not usable from Java

### ISSUE THREAD

**Issue by tanmatra** [belluzj/fantasque-sans#65]
It has very strange metrics:
![fantasque-1](https://cloud.githubusercontent.com/assets/708023/13263528/f5799a50-da7a-11e5-895a-609c9f981f4c.png)

Or with subpixel antialising:
![fantasque-2](https://cloud.githubusercontent.com/assets/708023/13263567/1ae81de8-da7b-11e5-863d-ad1dfe84340a.png)

And it ever is not showing in list of available font in latest IntelliJ IDEA.

**Comment by belluzj** [comment]
Thanks for your report, I will try to reproduce the problem on my machine. Some questions : which version of windows is this? How did you get the font? If you downloaded it from the Github release page, did you get the standard build or the half-em for chinese users? Did you install the .ttf or the .otf? Thanks in advance for the details.

**Comment by tanmatra** [comment]
Well, it was OTF version. I reintstalled TTF version, and now all seems fine. Sorry to bother you.
