### ISSUE TITLE
some glyphs unsuitable for programming (from Debian BTS)

### ISSUE THREAD

**Issue by copyninja** [belluzj/fantasque-sans#68]
Hi @belluzj 

I'm the maintainer of this font in Debian and I received the following bug report today. 

> The font Fantasque Sans Mono is described as being suitable for
> programmers. However, its glyphs fail to sufficiently distinguish
> important characters.
> 
> In particular:
> 
> * The glyphs for accent characters <U+0060 `>, <U+00B4 ´> do not match
>   correctly. They should be left-right mirror images, but instead the
>   “grave” accent incorrectly looks like a single-open-quote glyph.
> 
> * The single-quote characters <U+0027 '>, <U+2018 ‘>, <U+2019 ’> have
>   glyphs that are virtually indistinguishable. The <U+0027 '> glyph
>   should not be left or right biased.
> 
>   By comparison, the double-quote characters <U+0022 ">, <U+201C “>,
>   <U+201D ”> have conventional and sufficiently distinct glyphs.
> 
> There may be other glyphs which in this font are unhelpful to
> programmers, but these have caught my attention.

The bug is at https://bugs.debian.org/820397

**Comment by belluzj** [comment]
Hi ! Thanks for making my font available to Debian users :)

I think most of the problems reported here have been fixed in 1.7.0 and further improved in 1.7.1 (c.f. https://github.com/belluzj/fantasque-sans/issues/57). I would advise that the OP upgrade their fonts to the latest version and check whether it solves their problem.

**Comment by copyninja** [comment]
Thank you @belluzj I've uploaded 1.7.1 to archive and I've closed the bug in Debian BTS. I will wait for a while to get response back from reporter and if there is still issue I'll reopen this bug.
