### ISSUE TITLE
Please consider adding ≤ and ≥

### ISSUE THREAD

**Issue by nanis** [belluzj/fantasque-sans#69]
Thank you very much for your work on Fantasque Sans Mono.

Would you consider adding ≤ and ≥?

I tried, but apparently copying the less than sign and trying to draw a good looking line under it still requires a design sense which I do not possess.

Of course, the entire [Mathematical Operators Block](https://en.wikipedia.org/wiki/Mathematical_Operators) would be nice, but "less than or equal to" and "greater than or equal to" seem to be the most immediately useful ;-)

**Comment by belluzj** [comment]
I will add it in the next version (not sure when). Thanks for reporting!

**Comment by nanis** [comment]
Thank you. I use FSM as my main monospaced font and it is a pleasure. I really appreciate your work.
