### ISSUE TITLE
Would you consider increasing the line spacing in Fantasque Sans Mono?

### ISSUE THREAD

**Issue by sixpointzero** [belluzj/fantasque-sans#72]
Thanks for creating and releasing such an awesome font!

I was using Fantasque Sans Mono for the past few weeks when I noticed that the line spacing is a bit uncomfortable for me. Here are the relevant screenshots.

**Fantasque Sans Mono Regular 14**

![fantasque 14](https://cloud.githubusercontent.com/assets/19494538/15917932/f33b8918-2e1e-11e6-8da5-f804126a6cc6.png)

**Office Code Pro Regular 14**

![office code pro 14](https://cloud.githubusercontent.com/assets/19494538/15917946/22f0c9c0-2e1f-11e6-928c-f4b42d366222.png)

**Fantasque Sans Mono Regular 18**

![fantasque 18](https://cloud.githubusercontent.com/assets/19494538/15917958/39b79274-2e1f-11e6-9636-ab105ccc1b2d.png)

I'm not really familiar with the relevant font terminology but I find that the vertical line spacing between characters is a bit lesser than it should be.  The line spacing in the Office Code Pro seems to be comfortable. What do you think?

**Comment by belluzj** [comment]
Hi!

Yes indeed, the lines are tightly packed together in this font, but I don't plan to change that now. I'm sure your terminal emulator or your text editor allows you to modify the line height in some way.

Later (not sure when), I plan to migrate to a more powerful build system and maybe then I will provide some alternative downloads with different line heights.

**Comment by sixpointzero** [comment]
> I'm sure your terminal emulator or your text editor allows you to modify the line height in some way.

Well, my terminal emulator doesn't. Maybe Emacs does but it would be a hack rather than a fix.

If you don't plan on doing this now, maybe you could give me some instructions to increase the space between lines myself. I have installed FontForge, cloned your repo, and learned that I might be able to do what I want by going to `Element -> Font info -> OS/2 -> Metrics` but I don't know what values I should change.

Also, which Sans font would you recommend that should be used with Fantasque Sans Mono?

**Comment by belluzj** [comment]
Here are tips on how to use the FontForge interface (to take with a grain of salt, the last time I modified those values was a long time ago and I remember suffering to get consistent results across platforms). In red it's the current settings and the rules they must respect, in green it's an example of how you could modify them. Sorry, the interface is in French.

![fontforge](https://cloud.githubusercontent.com/assets/3616772/16170136/d9b14f2e-3548-11e6-8b70-f79dbda4465b.png)

As for the pairing with a sans, there is the obvious choice of Fantasque Sans, but I do not maintain this font as much as Fantasque Sans Mono, so it only has one weight, no Greek, no Cyrillic, the kerning is not all good... a the font looks goofy, even more than the mono version. Have a look:

![Pairing with Fantasque Sans and Lato](https://cloud.githubusercontent.com/assets/3616772/16170129/b8b93bce-3548-11e6-9d76-49caf81ca32d.png)

If you want good looking and free sans-serif fonts, you can have a look at: https://www.fontsquirrel.com/fonts/list/find_fonts?filter[classifications][0]=sans+serif&sort=popular

Some of my favorites are Lato (used for the title above), Alegreya Sans, Work Sans, Fira Sans... but I can't guarantee that they can be paired with this font. You'll have to test and see for yourself :)

**Comment by sixpointzero** [comment]
Thanks a lot! I'll starting tweaking the font when I can and tell you if I come up with acceptable results.

I was constantly switching between Alegreya Sans and Fira Sans and wasn't satisfied with either of them. I recently found [Signika](https://www.fontsquirrel.com/fonts/signika) on the same link that you suggested. I think it goes very well with Fantasque Sans Mono.
