### ISSUE TITLE
Weird merging of unicode characters from GCC warning output

### ISSUE THREAD

**Issue by dstl1128** [belluzj/fantasque-sans#73]
Using Fantasque Mono in KDE Konsole:
![fantasque-error](https://cloud.githubusercontent.com/assets/646551/15995507/1058d70c-314f-11e6-96d7-b101ab29e231.png)

Using Ubuntu Mono:
![ubuntu-mono](https://cloud.githubusercontent.com/assets/646551/15995511/1c960864-314f-11e6-993a-9355496e1ca1.png)

**Comment by belluzj** [comment]
This looks like a duplicate of #59. Did you build the font yourself with an old version of FontForge? Can you reproduce the problem with the .ttf files from the [official download](https://github.com/belluzj/fantasque-sans/releases/latest)?

**Comment by dstl1128** [comment]
Tested with 
* https://fontlibrary.org/en/font/fantasque-sans-mono and 
* the official download above

merged quote no longer happening. :+1:
