### ISSUE TITLE
Straight quote looks exactly like closing curly quote

### ISSUE THREAD

**Issue by phortuin** [belluzj/fantasque-sans#76]
Currently, there’s no discernable difference between a left curly quote and a straight quote:

![screen shot 2016-11-28 at 15 45 15](https://cloud.githubusercontent.com/assets/137299/20672471/baf6a002-b581-11e6-8bbf-5428e876e682.png)

> Line 1 is a straight quote `'`, line 2 is a closing curly quote `’`

When coding, one might not often find use for a curly quote, but when writing documentation interspersed with code snippets — especially when your Markdown editor automatically substitutes curly quotes — not seeing a difference between these can fast become messy.

**Comment by belluzj** [comment]
I think you're not using the latest version, because that problem is solved as of 1.7.1. See here for a preview of the result: https://github.com/belluzj/fantasque-sans/issues/57#issuecomment-166153003

**Comment by phortuin** [comment]
That fixed it, weird though because I downloaded the font for the first time only a couple of days ago. Must have been some old version. Thanks
