### ISSUE TITLE
Using straight k in 1.7.1

### ISSUE THREAD

**Issue by superDuperCyberTechno** [belluzj/fantasque-sans#79]
How would I go about installing the font set with the straight lowercase k? I feel like an idiot for asking this, but I can't seem to fint the font file anywhere in the tarball.

**Comment by belluzj** [comment]
It's completely my fault, I haven't been working on this project for a while and never released a version of the font with the straight lowercase k as default. I will do it someday, when I upgrade my build system.

In the meantime, please look at alternative solutions from #67 

Closing in favor of #67

**Comment by belluzj** [comment]
I released a version with the stylistic set pre-activated: https://github.com/belluzj/fantasque-sans/releases/download/v1.7.1/FantasqueSansMono_ss01.zip

**Comment by up0** [comment]
Thank you.  I love this font, and use it as my main font for terminal and coding.  The only thing that really bothered me was the letter "k".
