### ISSUE TITLE
Straight quotation mark's are indistinguishable from curly quotation marks

### ISSUE THREAD

**Issue by samcv** [belluzj/fantasque-sans#81]
![screenshot_20170627_003225](https://user-images.githubusercontent.com/20145557/27575927-26a66f50-5ad0-11e7-8033-28dc496dc921.png)

I like this font, but this issue prevents my from using it while coding. I program Perl 6 which allows you to use curly single or double quotes as well as straight quotes, so not being able to tell which type of quote is on the screen is a huge issue. If you see the screenshot above, you will find you cannot distungish any of those quotation marks. So if I am programming, I don't know whether I am dealing with a curly quote or a straight quote, forcing me to assume of guess which it is and hope I had guessed properly.

I'm fine with the rest of the font being kind of curly and fun, I like that. But when you cannot distungish between characters then it becomes an issue. The single quotes are the main issue, if you see below I compare fantasque sans to DejaVu Sans Mono:

Fantasque-sans:
![screenshot_20170627_001857](https://user-images.githubusercontent.com/20145557/27575342-47a235a6-5ace-11e7-9559-6d713c3f9b5b.png)

DejaVu Sans Mono:
![screenshot_20170627_002044](https://user-images.githubusercontent.com/20145557/27575424-96230a8e-5ace-11e7-80f4-bec3dbc58f05.png)

**Comment by belluzj** [comment]
You're in luck because this issue has been fixed for a very long time: see https://github.com/belluzj/fantasque-sans/issues/57#issuecomment-166153003

Just download the latest version of the font and enjoy: https://github.com/belluzj/fantasque-sans/releases/tag/v1.7.1

**Comment by samcv** [comment]
Yay! Awesome. Looks like Gentoo needs to update its font. I checked and they have version 2014.07… I'll have to make a bug ticket for it.
