### ISSUE TITLE
Request: ｢ ｣ U+FF62 U+FF63 quotes HALFWIDTH LEFT/RIGHT CORNER BRACKET

### ISSUE THREAD

**Issue by samcv** [belluzj/fantasque-sans#82]
These quotation marks are part of the Perl 6 programming language for literal quoting where nothing needs to be escaping. Would be cool if they were built into the font.

They are a pretty easy shape, just an L type shape in the very top left and bottom right side.

```perl6
my $var = ｢no\need\\to"escape'anything｣;
```

**Comment by belluzj** [comment]
Indeed, will consider it. Thanks for your interest :)
