### ISSUE TITLE
p, q and u are offset by 1 pixel

### ISSUE THREAD

**Issue by cqql** [belluzj/fantasque-sans#94]
Hello,
yesterday I switched to your font and really enjoy it. The only thing is that the letters p, q and u are somehow offset a tiny bit in the normal weight as shown in the screenshot. This does not happen in the bold font. Do you have any idea why this could be? It did not find this effect on the example screenshots in the README.

I am using 1.7.2-no-k-loop.

Best,
Marten

![2018-05-17-15 34 43](https://user-images.githubusercontent.com/339165/40180852-1595239c-59e8-11e8-9073-ef8c07a8ea69.png)

**Comment by belluzj** [comment]
It's probably because those letters are a bit off, and also it may depend on your operating system & desktop environment & terminal emulator. Could I ask you which of those you're using?

**Comment by cqql** [comment]
Of course. I am running Arch Linux with i3 as a window manager. My terminal emulator is urxvt though the same thing happens in emacs' graphical mode and rofi, all of which I have set to use Fantasque Sans Mono. Do you have any idea what I could try to fix it or in which direction I should further investigate?

**Comment by cqql** [comment]
Disabling auto-hinting worked. I set the following in my `.Xresources`.

```
URxvt*font: xft:Fantasque Sans Mono:size=13:hinting=false
```

Now I just have to figure out how to get the same result in emacs. I tried to write a `fonts.conf` but could not get it to work.

```xml
<!-- fonts.conf -->
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="font">
    <test qual="all" name="family" compare="eq">
      <string>Fantasque</string>
    </test>
    <test qual="all" name="weight" compare="eq">
      <const>medium</const>
    </test>
    <edit name="autohint" mode="assign">
      <bool>false</bool>
    </edit>
  </match>
</fontconfig>
```

Thank you for your help.

![2018-05-17-16 31 52](https://user-images.githubusercontent.com/339165/40184177-e03bfd4e-59ef-11e8-8fe1-6e1a225743cb.png)
